version: "3.1"
services:
  database:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "3301:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=zikade3301
      - POSTGRES_DB=Modulhandbuch
volumes:
  database-data: