version: "3.1"
services:
  database:
    image: postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=zikade3301
      - POSTGRES_DB=Modulhandbuch
  module:
    build:
      context: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin

volumes:
  database-data: